// src/pages/student/keyword-learning/recommendedKeywords.js

const recommendedKeywords = [
  'giraffe',
  'frog',
  'octopus',
  'polar bear',
  'penguin',
  'hamster',
  'bear',
  'tail',
  'vet',
  'animals',
  'animal care center',
  'animal sounds in English',
  'animal sounds in different languages',
  'jacket',
  'handle',
  'basket',
  'umbrella',
  'pocket',
  'uniform',
  'volunteer',
  'guard',
  'gate',
  'superstar',
  'jeans',
  'coat',
  'sunglasses',
  'skin',
  'post office',
  'shop',
  'field trip',
  'park',
  'weekend',
  'fruit',
  'mouth',
  'nut',
  'goal',
  'sign',
  'happiness',
  'subject',
];

export default recommendedKeywords;